title: "Diccionario de Derecho Chileno"
description: "Repositorio de lemas del Derecho Chileno e Internacional"
lang: "es"
theme: minima
markdown: kramdown
baseurl: ""
url: "https://ddch.cl"

# Collections
collections:
  lemas:
    output: true
    permalink: /lemas/:title/
  ramas:
    output: true
    permalink: /ramas/:title/
  aforismos:
    output: true
    permalink: /aforismos/:title/
  recursos:
    output: true
    permalink: /recursos/:title/
  articulos:
    output: true
    permalink: /articulos/:title/


# Optional: keep site timezone for date formatting
timezone: "America/Santiago"


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
